server:
  address: ${SPRING_HOST}
  port: ${SPRING_PORT}
  forward-headers-strategy: framework

logging:
  level:
    root: warn
    org:
      hibernate: INFO
      springframework:
        web: debug

spring:
  application:
    name: littlepm-course-service
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # none, validate, update, create, create-drop

file:
  storage-dir: ${FILE_STORAGE_DIR:./uploads}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: true