/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package pm.little.api.controllers;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import pm.little.api.models.Finances;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-04T00:03:08.519382+02:00[Europe/Prague]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "finances", description = "APIs for managing finances related to projects and users.")
public interface FinancesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /finances : List all finances records
     *
     * @param limit Limit of the list (required)
     * @param offset Offset of the list (required)
     * @param userUuid Filter list responses by user UUID (optional)
     * @return A list of Finances (status code 200)
     */
    @Operation(
        operationId = "financesGet",
        summary = "List all finances records",
        tags = { "finances" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of Finances", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Finances.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/finances",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Finances>> financesGet(
        @NotNull @Parameter(name = "limit", description = "Limit of the list", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = true) Integer limit,
        @NotNull @Parameter(name = "offset", description = "Offset of the list", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = true) Integer offset,
        @Parameter(name = "user_uuid", description = "Filter list responses by user UUID", in = ParameterIn.QUERY) @Valid @RequestParam(value = "user_uuid", required = false) UUID userUuid
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"id\" : { \"project_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"investor_gave\" : 100.0, \"investor_return\" : 120.0 }, { \"id\" : { \"project_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"investor_gave\" : 100.0, \"investor_return\" : 120.0 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /finances : Create new finances record
     *
     * @param finances  (required)
     * @return Created finances (status code 200)
     */
    @Operation(
        operationId = "financesPost",
        summary = "Create new finances record",
        tags = { "finances" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Created finances", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Finances.class))
            })
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/finances",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Finances> financesPost(
        @Parameter(name = "Finances", description = "", required = true) @Valid @RequestBody Finances finances
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : { \"project_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"investor_gave\" : 100.0, \"investor_return\" : 120.0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /finances/{project_blueprint_uuid}/{user_uuid}/calculate : Calculate or recalculate finances
     *
     * @param projectBlueprintUuid The UUID of the project blueprint (required)
     * @param userUuid The UUID of the user (required)
     * @param finances  (required)
     * @return Calculated finances (status code 200)
     */
    @Operation(
        operationId = "financesProjectBlueprintUuidUserUuidCalculatePut",
        summary = "Calculate or recalculate finances",
        tags = { "finances" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Calculated finances", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Finances.class))
            })
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/finances/{project_blueprint_uuid}/{user_uuid}/calculate",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Finances> financesProjectBlueprintUuidUserUuidCalculatePut(
        @Parameter(name = "project_blueprint_uuid", description = "The UUID of the project blueprint", required = true, in = ParameterIn.PATH) @PathVariable("project_blueprint_uuid") UUID projectBlueprintUuid,
        @Parameter(name = "user_uuid", description = "The UUID of the user", required = true, in = ParameterIn.PATH) @PathVariable("user_uuid") UUID userUuid,
        @Parameter(name = "Finances", description = "", required = true) @Valid @RequestBody Finances finances
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : { \"project_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"investor_gave\" : 100.0, \"investor_return\" : 120.0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /finances/{project_blueprint_uuid}/{user_uuid} : Delete finances record
     *
     * @param projectBlueprintUuid The UUID of the project blueprint (required)
     * @param userUuid The UUID of the user (required)
     * @return No Content (status code 204)
     */
    @Operation(
        operationId = "financesProjectBlueprintUuidUserUuidDelete",
        summary = "Delete finances record",
        tags = { "finances" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content")
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/finances/{project_blueprint_uuid}/{user_uuid}"
    )
    
    default ResponseEntity<Void> financesProjectBlueprintUuidUserUuidDelete(
        @Parameter(name = "project_blueprint_uuid", description = "The UUID of the project blueprint", required = true, in = ParameterIn.PATH) @PathVariable("project_blueprint_uuid") UUID projectBlueprintUuid,
        @Parameter(name = "user_uuid", description = "The UUID of the user", required = true, in = ParameterIn.PATH) @PathVariable("user_uuid") UUID userUuid
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /finances/{project_blueprint_uuid}/{user_uuid} : Get finances record
     *
     * @param projectBlueprintUuid The UUID of the project blueprint (required)
     * @param userUuid The UUID of the user (required)
     * @return Finances (status code 200)
     */
    @Operation(
        operationId = "financesProjectBlueprintUuidUserUuidGet",
        summary = "Get finances record",
        tags = { "finances" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Finances", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Finances.class))
            })
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/finances/{project_blueprint_uuid}/{user_uuid}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Finances> financesProjectBlueprintUuidUserUuidGet(
        @Parameter(name = "project_blueprint_uuid", description = "The UUID of the project blueprint", required = true, in = ParameterIn.PATH) @PathVariable("project_blueprint_uuid") UUID projectBlueprintUuid,
        @Parameter(name = "user_uuid", description = "The UUID of the user", required = true, in = ParameterIn.PATH) @PathVariable("user_uuid") UUID userUuid
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : { \"project_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"investor_gave\" : 100.0, \"investor_return\" : 120.0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /finances/{project_blueprint_uuid}/{user_uuid} : Update finances record
     *
     * @param projectBlueprintUuid The UUID of the project blueprint (required)
     * @param userUuid The UUID of the user (required)
     * @param finances  (required)
     * @return Updated finances (status code 200)
     */
    @Operation(
        operationId = "financesProjectBlueprintUuidUserUuidPut",
        summary = "Update finances record",
        tags = { "finances" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated finances", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Finances.class))
            })
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/finances/{project_blueprint_uuid}/{user_uuid}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Finances> financesProjectBlueprintUuidUserUuidPut(
        @Parameter(name = "project_blueprint_uuid", description = "The UUID of the project blueprint", required = true, in = ParameterIn.PATH) @PathVariable("project_blueprint_uuid") UUID projectBlueprintUuid,
        @Parameter(name = "user_uuid", description = "The UUID of the user", required = true, in = ParameterIn.PATH) @PathVariable("user_uuid") UUID userUuid,
        @Parameter(name = "Finances", description = "", required = true) @Valid @RequestBody Finances finances
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : { \"project_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"investor_gave\" : 100.0, \"investor_return\" : 120.0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
