/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package pm.little.api.controllers;

import jakarta.annotation.Generated;
import pm.little.api.models.ProjectDaysMapper;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-04T00:03:08.519382+02:00[Europe/Prague]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "projects", description = "APIs for managing projects, day templates, and user progress tracking.")
public interface ProjectDaysMapperApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /project-days-mapper : List all project-day mappings
     *
     * @param limit Limit of the list (required)
     * @param offset Offset of the list (required)
     * @return A list of ProjectDaysMapper (status code 200)
     */
    @Operation(
        operationId = "projectDaysMapperGet",
        summary = "List all project-day mappings",
        tags = { "projects" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of ProjectDaysMapper", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ProjectDaysMapper.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/project-days-mapper",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<ProjectDaysMapper>> projectDaysMapperGet(
        @NotNull @Parameter(name = "limit", description = "Limit of the list", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = true) Integer limit,
        @NotNull @Parameter(name = "offset", description = "Offset of the list", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = true) Integer offset
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"id\" : { \"project_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"day_blueprint_uuid\" : \"557c482c-8bb5-4a65-9bef-848a953238ae\" }, \"sortOrder\" : 1 }, { \"id\" : { \"project_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"day_blueprint_uuid\" : \"557c482c-8bb5-4a65-9bef-848a953238ae\" }, \"sortOrder\" : 1 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /project-days-mapper : Create a new project-day mapping (admin only)
     *
     * @param projectDaysMapper  (required)
     * @return Created project-day mapping (status code 200)
     */
    @Operation(
        operationId = "projectDaysMapperPost",
        summary = "Create a new project-day mapping (admin only)",
        tags = { "projects" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Created project-day mapping", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProjectDaysMapper.class))
            })
        },
        security = {
            @SecurityRequirement(name = "admin_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/project-days-mapper",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<ProjectDaysMapper> projectDaysMapperPost(
        @Parameter(name = "ProjectDaysMapper", description = "", required = true) @Valid @RequestBody ProjectDaysMapper projectDaysMapper
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : { \"project_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"day_blueprint_uuid\" : \"557c482c-8bb5-4a65-9bef-848a953238ae\" }, \"sortOrder\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /project-days-mapper/{project_blueprint_uuid}/{day_blueprint_uuid} : Delete project-day mapping (admin only)
     *
     * @param projectBlueprintUuid The UUID of the project blueprint (required)
     * @param dayBlueprintUuid The UUID of the day blueprint (required)
     * @return No Content (status code 204)
     */
    @Operation(
        operationId = "projectDaysMapperProjectBlueprintUuidDayBlueprintUuidDelete",
        summary = "Delete project-day mapping (admin only)",
        tags = { "projects" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content")
        },
        security = {
            @SecurityRequirement(name = "admin_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/project-days-mapper/{project_blueprint_uuid}/{day_blueprint_uuid}"
    )
    
    default ResponseEntity<Void> projectDaysMapperProjectBlueprintUuidDayBlueprintUuidDelete(
        @Parameter(name = "project_blueprint_uuid", description = "The UUID of the project blueprint", required = true, in = ParameterIn.PATH) @PathVariable("project_blueprint_uuid") UUID projectBlueprintUuid,
        @Parameter(name = "day_blueprint_uuid", description = "The UUID of the day blueprint", required = true, in = ParameterIn.PATH) @PathVariable("day_blueprint_uuid") UUID dayBlueprintUuid
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /project-days-mapper/{project_blueprint_uuid}/{day_blueprint_uuid} : Get a specific project-day mapping
     *
     * @param projectBlueprintUuid The UUID of the project blueprint (required)
     * @param dayBlueprintUuid The UUID of the day blueprint (required)
     * @return A single ProjectDaysMapper (status code 200)
     */
    @Operation(
        operationId = "projectDaysMapperProjectBlueprintUuidDayBlueprintUuidGet",
        summary = "Get a specific project-day mapping",
        tags = { "projects" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A single ProjectDaysMapper", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProjectDaysMapper.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/project-days-mapper/{project_blueprint_uuid}/{day_blueprint_uuid}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<ProjectDaysMapper> projectDaysMapperProjectBlueprintUuidDayBlueprintUuidGet(
        @Parameter(name = "project_blueprint_uuid", description = "The UUID of the project blueprint", required = true, in = ParameterIn.PATH) @PathVariable("project_blueprint_uuid") UUID projectBlueprintUuid,
        @Parameter(name = "day_blueprint_uuid", description = "The UUID of the day blueprint", required = true, in = ParameterIn.PATH) @PathVariable("day_blueprint_uuid") UUID dayBlueprintUuid
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : { \"project_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"day_blueprint_uuid\" : \"557c482c-8bb5-4a65-9bef-848a953238ae\" }, \"sortOrder\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /project-days-mapper/{project_blueprint_uuid}/{day_blueprint_uuid} : Update a specific project-day mapping (admin only)
     *
     * @param projectBlueprintUuid The UUID of the project blueprint (required)
     * @param dayBlueprintUuid The UUID of the day blueprint (required)
     * @param projectDaysMapper  (required)
     * @return Updated mapping (status code 200)
     */
    @Operation(
        operationId = "projectDaysMapperProjectBlueprintUuidDayBlueprintUuidPut",
        summary = "Update a specific project-day mapping (admin only)",
        tags = { "projects" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated mapping", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProjectDaysMapper.class))
            })
        },
        security = {
            @SecurityRequirement(name = "admin_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/project-days-mapper/{project_blueprint_uuid}/{day_blueprint_uuid}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<ProjectDaysMapper> projectDaysMapperProjectBlueprintUuidDayBlueprintUuidPut(
        @Parameter(name = "project_blueprint_uuid", description = "The UUID of the project blueprint", required = true, in = ParameterIn.PATH) @PathVariable("project_blueprint_uuid") UUID projectBlueprintUuid,
        @Parameter(name = "day_blueprint_uuid", description = "The UUID of the day blueprint", required = true, in = ParameterIn.PATH) @PathVariable("day_blueprint_uuid") UUID dayBlueprintUuid,
        @Parameter(name = "ProjectDaysMapper", description = "", required = true) @Valid @RequestBody ProjectDaysMapper projectDaysMapper
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : { \"project_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"day_blueprint_uuid\" : \"557c482c-8bb5-4a65-9bef-848a953238ae\" }, \"sortOrder\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
